// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdvisorySeverity } from "./AdvisorySeverity";
import type { RuleId } from "./RuleId";

/**
 * Phase 7 — Stage 7.5 諮詢性發現(Channeling / Ch9 Advanced Rules)。
 */
export type AdvisoryFinding = { 
/**
 * 對應的 RuleId(Ch5_Channeling_* / Ch9_*)
 */
rule_id: RuleId, 
/**
 * 嚴重度(Info / Warning / Strong — 對應 spec 「應」 vs 「必」 vs 「絕不」)
 */
severity: AdvisorySeverity, 
/**
 * 人類可讀訊息(機械式陳述,對齊 cores_overview §6.1.1 禁主觀詞彙)
 */
message: string, };
