// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlternationCheck } from "./AlternationCheck";

/**
 * Alternation 5 軸聚合結果(v4.1 從單軸 holds: bool 升 5-axis,對齊
 * spec §Rule of Alternation 與 `output.rs::AlternationAxis` 既有 enum)。
 *
 * 5 軸:Price / Time / Severity / Intricacy / Construction。
 * Phase 1 PR 只有 Construction 軸被 validator dispatch;v4.1 補完其他 4 軸
 * 由 `classifier::structural_facts::alternation` 直接由 monowave metrics 計算。
 */
export type AlternationFact = { 
/**
 * Price 軸:W2 / W4 retracement % 差異是否顯著(預設門檻 ≥ 25%)
 */
price: AlternationCheck, 
/**
 * Time 軸:W2 / W4 持續時間是否顯著不同(預設 ≥ 1.5x 或 ≤ 0.67x)
 */
time: AlternationCheck, 
/**
 * Severity 軸:W2 / W4 retracement 深淺嚴格度(deep vs shallow,預設深 ≥ 61.8%、淺 < 38.2%)
 */
severity: AlternationCheck, 
/**
 * Intricacy 軸:W2 / W4 子結構複雜度(以 :3 構型內 sub-monowave 推估 — 簡化版,V4.x 細化)
 */
intricacy: AlternationCheck, 
/**
 * Construction 軸:W2 / W4 :5/:3 構型是否不同(對齊 Phase 1 既有 validator 邏輯)
 */
construction: AlternationCheck, 
/**
 * 全 5 軸聚合:任一軸 `Failed` → false;任一軸 `Confirmed` + 其他 NotApplicable → true
 */
overall_holds: boolean, };
