// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Alternation 的「軸」(neely_rules.md §Rule of Alternation)。
 * Phase 1 PR:只 Construction 軸實際被引用(W2/W4 alternation 用 Construction),
 * 其他 axis variant 留後續 PR 用。
 */
export type AlternationAxis = "Price" | "Time" | "Severity" | "Intricacy" | "Construction";
