// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Alternation 單軸檢查結果(v4.1 — 對齊 NEoWave §Rule of Alternation 五軸)。
 */
export type AlternationCheck = "Confirmed" | "NotApplicable" | "Failed";
