// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssumptionSource } from "./AssumptionSource";

/**
 * E1:單一引擎假設(名稱 + 數值 + 來源)。
 */
export type Assumption = { name: string, value: number, source: AssumptionSource, };
