// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * E1 假設來源分類(m3Spec/wave_judgment_loop.md §3)。
 */
export type AssumptionSource = "Canon" | "Interpretation" | "Engineering";
