// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Certainty — Structure Label 的封裝強度(neely_rules.md §封裝慣例 343-346 行)。
 *
 * - Primary(無封裝):主要選項(機率最高)
 * - Possible(`(...)`):可能但機率較低
 * - Rare(`[...]`):罕見,僅在極特定條件成立時才考量
 * - MissingWaveBundle(`?` 後綴):missing-wave 場景的束帶標記
 *   (對齊 neely_rules.md §1054-1057「missing wave 標記慣例」:成組捆綁,一個被棄整組刪)
 */
export type Certainty = "Primary" | "Possible" | "Rare" | "MissingWaveBundle";
