// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ch6 Post-Constructive 確認狀態(neely_ch6_gate_running_fix spec)。
 *
 * - `Confirmed`:Stage 1 + Stage 2 皆通過(市場已確認形態完成)
 * - `Pending`:接受但待後續驗證(Stage 2 未完成,或該形態族無 Stage 1 硬閘)
 * - `Deferred`:post-pattern 葉為空(live edge)或資訊不足,無法評估
 *
 * 1.1.1 及以前的 snapshot 無此欄 — 讀取端缺欄一律視為 `Deferred`,不回填。
 */
export type Ch6Status = "Confirmed" | "Pending" | "Deferred";
