// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Channeling 證據細節(v4.1 — 補 evidence 欄位給 Aggregation 看)。
 */
export type ChannelingFact = { holds: boolean, 
/**
 * 各 trendline touchpoints / channel 偵測證據(對齊 spec §Ch5/Ch9 Channeling
 * 5 條 trendlines:0-2 / 1-3 / 2-4 / 0-B / B-D)
 */
evidence: Array<string>, };
