// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CombinationKind = "DoubleZigzag" | "DoubleCombination" | "DoubleFlat" | "TripleZigzag" | "TripleCombination" | "DoubleThree" | "DoubleThreeCombination" | "DoubleThreeRunning" | "TripleThree" | "TripleThreeCombination" | "TripleThreeRunning";
