// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Compaction v2 tiling-round 引擎診斷(m3Spec/neely_compaction_v2.md §5/§6)。
 *
 * `compaction::round_engine::run` 每次 compute 隨行:
 * - I1–I6 不變量違反計數(§2.2;任一 > 0 = 引擎 bug)
 * - `level_cap_hit`(A-8:輪數上限造成的枚舉缺漏,由靜默轉可觀察)
 * - §6.1 邊界重評 / §6.2 Complexity / §6.3 Degree 對映等觀測欄
 */
export type CompactionV2Diagnostics = { 
/**
 * 引擎版本 tag(例 "tiling-round-v2")
 */
engine: string, 
/**
 * base tiling 節點數(非 Neutral monowaves + 合成葉)
 */
base_tiling_len: number, 
/**
 * Neutral 段併入前一 directional 節點的次數(§5.2 合成葉橋接)
 */
neutral_bridged: number, 
/**
 * 開頭 Neutral 無前節點可併,直接排除的數量(記 diagnostics,§5.2)
 */
leading_neutral_dropped: number, 
/**
 * 實際發生聚合的輪數
 */
rounds_run: number, 
/**
 * 收斂後 tiling pool 大小(beam 截斷後)
 */
tiling_count: number, 
/**
 * A-8:觸 max_compaction_levels 上限跳出(非零聚合收斂)
 */
level_cap_hit: boolean, 
/**
 * 引擎逾時(同步反映至頂層 `compaction_timeout`;以當前已凍結內容返回)
 */
timed_out: boolean, 
/**
 * W1/I2 防衛在 release 記到的違反數(> 0 = 引擎 bug)
 */
w1_violations: number, 
/**
 * round 內新分支 materialize 上限(round_beam_size × 8)截斷的輪數。
 * 工程護欄非 Neely 語意;> 0 = 該檔枚舉受截斷,Gate 觀測項(A-8 精神)。
 * G2.2 起截斷前先依 beam 鍵近似分數全窗排序,無時間軸偏置
 */
round_branch_cap_hits: number, 
/**
 * W5:被 Ch5 端點重驗(overall_pass = false)拒絕的唯一視窗數
 * (完整 RuleRejection 進 `NeelyDiagnostics.rejections`,§4.1)
 */
w5_rejected_windows: number, 
/**
 * Ch6 Stage 1 硬閘拒絕的唯一 (視窗, kind) 數(neely_ch6_gate_running_fix;
 * 與 `w5_rejected_windows` 分計,gate 報告 Ch5/Ch6 歸因不混淆)
 */
ch6_rejected_kinds: number, 
/**
 * G2.2 Q3 雙軌實驗(§12):完成端點版 vs bars 反查版比對的唯一 5-窗數
 */
q3_windows: number, 
/**
 * Q3:Overlap / 回測判定翻轉的視窗數;翻轉率 = q3_flips / q3_windows,
 * > 5%(spec 初始門檻)→ 落 bars 反查
 */
q3_flips: number, 
/**
 * degree_level → 節點數(canonical 去重後;key 為字串供 JSONB 直取)
 */
node_count_by_level: { [key in string]?: number }, 
/**
 * G2.4 Gate v3:pattern tag → 節點數(canonical 去重後)— §9.2 Terminal
 * Impulse 存在性門檻與形態分布報告的資料源
 */
node_count_by_pattern: { [key in string]?: number }, 
/**
 * I1–I6 違反計數(key "I1".."I6")
 */
invariant_violations: { [key in string]?: number }, 
/**
 * G2.3 §6.1 邊界波重評(D-4):完成比對的 (parent 首/末子波, 真鄰居) 對數
 */
boundary_pairs_checked: number, 
/**
 * §6.1:比值落 [0.236, 0.382) ∪ (2.618, 4.236] 的 Advisory(Info)數
 */
boundary_advisory_info: number, 
/**
 * §6.1:比值落 [0.236, 4.236] 外的 Advisory(Warning)數(不拒絕聚合)
 */
boundary_advisory_warning: number, 
/**
 * §6.1:tiling 首/末 parent 無對應鄰居(或零幅度不可比)跳過的側數
 */
boundary_sides_skipped: number, 
/**
 * G2.3 §6.2 Complexity 真算:complexity level(0..=3)→ 節點數
 * (canonical 去重後收集 forest;取代硬寫 Complex 的分布觀測)
 */
complexity_count_by_level: { [key in string]?: number }, 
/**
 * §6.2:子樹內出現 ≥ 3 種不同 Complexity Level 之 Impulse 段的節點數
 */
triplexity_nodes: number, 
/**
 * G2.3 §6.3 Degree 對映(ceiling 錨定):degree_level → Degree 名
 * (輸出展示用;不回饋任何接受條件)
 */
degree_map: { [key in string]?: string }, 
/**
 * §6.3:超出 11 級下界被夾至 SubMicro 的 level 數(記 diagnostics)
 */
degree_clamped_levels: number, elapsed_us: bigint, };
