// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MonowaveSummary } from "./MonowaveSummary";

/**
 * Stage 12 cross_timeframe_hints — 各 monowave 摘要,供 Aggregation Layer 跨 Timeframe 比對。
 *
 * 對齊 architecture §8.6:Neely Core 本來就有完整 monowave 資訊,直接輸出比 Aggregation
 * 重新解析 `structural_snapshots` 高效。
 */
export type CrossTimeframeHints = { 
/**
 * 本次分析的 Timeframe
 */
timeframe: "Daily" | "Weekly" | "Monthly" | "Quarterly", 
/**
 * 各 monowave 的摘要
 */
monowave_summaries: Array<MonowaveSummary>, };
