// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Degree } from "./Degree";

/**
 * Stage 11 Degree Ceiling — 依資料量推導本次分析能達到的最高 Degree。
 *
 * 對齊 architecture §8.5 + §13.3:
 *   - < 1 年 → SubMinuette
 *   - 1-3 年 → Minuette / Minute
 *   - 3-10 年 → Minor / Intermediate
 *   - 10-30 年 → Primary
 *   - > 30 年 → Cycle / Supercycle
 *
 * **為何重要**(spec §8.5):台股大部分個股上市 5-15 年,根本到不了 Cycle 級別。
 * Aggregation 層可據此自動降低顯示的 Degree 標籤,避免「短歷史股票被標為 Supercycle」誤導。
 */
export type DegreeCeiling = { 
/**
 * 本次分析依資料量可達到的最高 Degree
 */
max_reachable_degree: Degree, 
/**
 * 推導原因說明(例:"data spans 8 years, daily timeframe reaches Minor at best")
 */
reason: string, };
