// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Neely 11 級 Degree 體系(architecture §8.5)。
 *
 * 對齊精華版 Ch7 11 級體系,由小至大列序。
 */
export type Degree = "SubMicro" | "Micro" | "SubMinuette" | "Minuette" | "Minute" | "Minor" | "Intermediate" | "Primary" | "Cycle" | "Supercycle" | "GrandSupercycle";
