// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Zigzag DETOUR Test 對 wave_count == 3 candidate 的 annotation
 * 對齊 m3Spec/neely_rules.md §Zigzag DETOUR Test(1283-1285 行)。
 */
export type DetourAnnotation = { 
/**
 * 對應 candidate id
 */
candidate_id: string, 
/**
 * 若 detour 後 5-wave Trending Impulse 結構成立,提供替代 monowave_indices(共 5 個)
 */
impulse_alternative: Array<number> | null, };
