// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Emulation 類型 — 視覺上相似但實際結構不同的 pattern 偽裝。
 *
 * **v4.5.1(2026-05-19)**:加 `ZigzagAsFlatFailure` variant,對齊
 * `m3Spec/neely_rules.md` 2337-2342 行 Zigzag wave-c 規則。
 */
export type EmulationKind = "RunningDoubleThreeAsImpulse" | "DiagonalAsImpulse" | "TriangleAsFailure" | "FirstExtAsTerminal" | "ZigzagAsFlatFailure" | "FlatAsZigzag" | "CombinationAsImpulse" | "Generic";
