// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EmulationKind } from "./EmulationKind";

/**
 * Emulation Suspect — 形態偽裝候選。
 */
export type EmulationSuspect = { 
/**
 * 對應的 Scenario id(若可定位)
 */
scenario_id: string | null, kind: EmulationKind, 
/**
 * 機械式陳述(對齊 cores_overview §6.1.1 禁主觀詞彙)
 */
message: string, };
