// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ch9 Exception Rule Aspect 1 的三個情境(neely_rules.md 1980-1986 行)。
 */
export type ExceptionSituation = "MultiwaveEnd" | "TerminalW5OrC" | "TriangleEntryExit";
