// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubdivisionStatus } from "./SubdivisionStatus";
import type { WaveNumber } from "./WaveNumber";

/**
 * Extension Subdivision Pair:延伸段位置 + 獨立性判定 + 倍率。
 *
 * 對齊 spec §Ch8 Independent Rule(`neely_rules.md` §Ch8 Complex Polywaves)。
 * v4.1 加入 StructuralFacts 給 Aggregation Layer 對 Ch8 Multiwave / X-wave 偵測伸縮判斷。
 */
export type ExtensionSubdivisionPair = { 
/**
 * 延伸段在 5-wave Impulse 中的位置(W1 / W3 / W5)
 */
extended_wave: WaveNumber, 
/**
 * 延伸段獨立性
 */
status: SubdivisionStatus, 
/**
 * 延伸段倍率 = ext.magnitude / max(non-ext.magnitude)
 */
extension_ratio: number, };
