// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FibZone = { label: string, low: number, high: number, source_ratio: number, };
