// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * FlatKind 8-variant(spec r5 line 1161 + neely_rules.md line 2157-2239 + Appendix B 項 A)。
 *
 * Phase 16(2026-05-14)重構:r4 3-variant → r5 7-variant 具體形態變體;
 * v4.1(2026-05-19)補完 Appendix B 項 A 123.6% Strong b-wave 中間檻 → 8-variant。
 *
 * 判定規則(spec line 2157-2239 + 2024-2034 + Appendix B 項 A):
 * | Variant          | b/a 範圍              | c 行為           | Power |
 * |------------------|-----------------------|------------------|-------|
 * | Common           | 81%–100%              | c ≥ 100% × b     | 0     |
 * | BFailure         | 61.8%–81%             | c ≥ 100% × b     | 0     |
 * | CFailure         | 81%–100%              | c < 100% × b     | -1    |
 * | DoubleFailure    | 61.8%–81%             | c < 100% × b     | -2    |
 * | Irregular        | 100%–**123.6%**       | c ≥ 100% × b     | -1    |
 * | IrregularStrongB | **123.6%–138.2%**     | c ≥ 100% × b     | -1    |
 * | IrregularFailure | > 138.2%              | c < 100% × b     | -2    |
 * | Elongated        | ≥ 138.2%(Triangle/Terminal 內) | c > a | +1   |
 *
 * **Appendix B 項 A 123.6% 中間檻語意**:b/a 超過 123.6% 屬 Strong b-wave 區段,
 * 對 post-pattern Impulse 有更強約束(spec §Ch10 Power Rating Lookup),
 * 仍走 Power -1 但 PostBehavior 細節較嚴(預留 V4.x table.rs 補微調)。
 *
 * 由 `classifier::flat_classifier::classify_flat` 從 monowave magnitudes 推導。
 */
export type FlatKind = "Common" | "BFailure" | "CFailure" | "DoubleFailure" | "Irregular" | "IrregularStrongB" | "IrregularFailure" | "Elongated";
