// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ch11 Flat 全部變體(neely_rules.md §Corrective — Flat 全部變體 2191-2322 行)。
 * 用於 `RuleId::Ch11_Flat_Variant_Rules` 區分各 Flat 變體規則。
 */
export type FlatVariant = "Common" | "Elongated" | "Irregular" | "StrongB" | "CFailure" | "BFailure" | "DoubleFailure" | "IrregularFailure" | "DoubleFlat" | "RunningCorrection";
