// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ch6 / Ch11 Impulse 延伸段位置(對映 neely_rules.md §Extension Rule 1302-1308 行)。
 * 用於 `RuleId::Ch6_Impulse_Stage2` / `Ch11_Impulse_WaveByWave` /
 * `Ch11_Terminal_WaveByWave` 區分依延伸段位置(1st / 3rd / 5th / none)的不同變體規則。
 */
export type ImpulseExtension = "First" | "Third" | "Fifth" | "NonExtended";
