// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * E4:live-edge 互斥候選歧義(count = 互斥候選數;kinds = 去重 pattern tag;
 * degree_level = 候選所在的最大 degree)。無 live-edge 候選 → 全零/空。
 */
export type LiveEdgeAmbiguity = { count: number, kinds: Array<string>, degree_level: number, };
