// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Missing Wave 位置分類(spec 1055-1057 行)。
 */
export type MissingWavePosition = "M1Center" | "M0Center" | "M2Endpoint" | "Ambiguous";
