// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MissingWavePosition } from "./MissingWavePosition";
import type { StructureLabel } from "./StructureLabel";

/**
 * Missing Wave Suspect — 從 P2 已標的 MissingWaveBundle certainty 萃取的結構化資訊。
 *
 * 對齊 spec 1054-1057 行「missing wave 標記慣例 — 標記成組捆綁」。
 */
export type MissingWaveSuspect = { 
/**
 * 對應的 monowave index(P2 標 bundle 的 monowave)
 */
monowave_idx: number, 
/**
 * missing wave 位置(M1Center / M0Center / M2Endpoint / Ambiguous)
 */
position: MissingWavePosition, 
/**
 * bundle 中所有 missing-wave 標記 labels(必須成組保留)
 */
bundle_labels: Array<StructureLabel>, 
/**
 * 機械式陳述(對齊 cores_overview §6.1.1 禁主觀詞彙)
 */
message: string, };
