// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 單一 monowave 的跨 Timeframe 摘要(architecture §8.6)。
 */
export type MonowaveSummary = { 
/**
 * 對應 classified_monowaves 的 index
 */
monowave_index: number, 
/**
 * 起訖日期
 */
date_range: [string, string], 
/**
 * Structure Label 候選清單(從 P2 Pre-Constructive 標的 candidates)
 * 例:[":L5", ":F3"]
 */
structure_label_candidates: Array<string>, 
/**
 * 起訖價格區間(start_price, end_price)
 */
price_range: [number, number], };
