// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StructureLabelCandidate } from "./StructureLabelCandidate";

/**
 * Phase 15 新增:每 monowave 的 Pre-Constructive structure label set。
 *
 * 對齊 m3Spec/neely_core_architecture.md §9.1 line 859。
 * 包裝 `ClassifiedMonowave.structure_label_candidates`,加上 monowave 在 Scenario 內的位置 index。
 *
 * **v4.x Item 4(2026-05-20)Pre-Constructive 2-pass diagnostics union**:
 * 加 `classified_index`(global slice index)讓 lib.rs Stage 8.5 Pass 2 完成後
 * 可逆查回該 monowave + 加 `pass1_only_labels` 暴露 Pass 2 polywave-aware run
 * 丟棄的 Pass 1 候選(對齊 spec「Pass 2 candidates 較 accurate」設計但保留
 * Pass 1 diagnostic trail)。
 */
export type MonowaveStructureLabels = { 
/**
 * 該 monowave 在 scenario candidate 內的索引(0..wave_count)
 */
monowave_index: number, 
/**
 * **v4.x Item 4**:該 monowave 在 lib.rs `classified` slice 的全域索引。
 * 由 classifier `build_monowave_structure_labels` 從 `WaveCandidate.monowave_indices`
 * 反查填入,供 Stage 8.5 post-Pass-2 refill loop lookup。
 */
classified_index: number, 
/**
 * Pre-Constructive Logic 給出的 candidate labels(可有多個,不互斥)。
 *
 * **v4.x Item 4 後語意**:Stage 5 classify 時填 Pass 1 result;Stage 8.5
 * Pass 2 完成後 refill 為 Pass 2 result(對齊 spec「Pass 2 較 accurate」)。
 */
labels: Array<StructureLabelCandidate>, 
/**
 * **v4.x Item 4**:Pass 1 找到但 Pass 2 (post-Compaction polywave-aware) 丟棄的
 * candidates。空 → Pass 1/Pass 2 結果一致(無 polywave 影響);
 * 非空 → Pass 2 因 polywave_size 反查丟棄了某些 Pass 1 候選。
 *
 * 比對僅依 `label`(certainty 升級不算 rejection,例 Possible → Primary)。
 * 由 `pre_constructive::run_pass2` 產 diff,lib.rs Stage 8.5 refill loop 寫入。
 *
 * 用途:
 *   - Diagnostic 透明化:LLM / Aggregation Layer 看 Pass 2 修正過程
 *   - Forecast 不確定性指標:diff 多 → Pass 1 / Pass 2 嚴重背離 → 預測穩定性低
 */
pass1_only_labels: Array<StructureLabelCandidate>, };
