// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CombinationKind } from "./CombinationKind";
import type { DiagonalKind } from "./DiagonalKind";
import type { FlatKind } from "./FlatKind";
import type { TriangleKind } from "./TriangleKind";
import type { ZigzagKind } from "./ZigzagKind";

export type NeelyPatternType = "Impulse" | { "Diagonal": { sub_kind: DiagonalKind, } } | { "Zigzag": { sub_kind: ZigzagKind, } } | { "Flat": { sub_kind: FlatKind, } } | { "Triangle": { sub_kind: TriangleKind, } } | { "Combination": { sub_kinds: Array<CombinationKind>, } } | "RunningCorrection";
