// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CrossTimeframeHints } from "./CrossTimeframeHints";
import type { DegreeCeiling } from "./DegreeCeiling";
import type { DetourAnnotation } from "./DetourAnnotation";
import type { EmulationSuspect } from "./EmulationSuspect";
import type { FibZone } from "./FibZone";
import type { MissingWaveSuspect } from "./MissingWaveSuspect";
import type { Monowave } from "./Monowave";
import type { NeelyDiagnostics } from "./NeelyDiagnostics";
import type { PatternBound } from "./PatternBound";
import type { ReverseLogicObservation } from "./ReverseLogicObservation";
import type { Round3PauseInfo } from "./Round3PauseInfo";
import type { RuleReference } from "./RuleReference";
import type { Scenario } from "./Scenario";
import type { TimeRange } from "./TimeRange";

export type NeelyCoreOutput = { stock_id: string, timeframe: "Daily" | "Weekly" | "Monthly" | "Quarterly", data_range: TimeRange, 
/**
 * Forest,**不**附 `primary` 欄位(§9.3)
 */
scenario_forest: Array<Scenario>, 
/**
 * monowave 序列 — 對外暴露給 trendline_core 唯一例外消費(§8.1)
 */
monowave_series: Array<Monowave>, diagnostics: NeelyDiagnostics, rule_book_references: Array<RuleReference>, 
/**
 * 資料充分性(歷史不足會導致大量 candidate 被 reject,實際是「無法判斷」)
 */
insufficient_data: boolean, 
/**
 * Phase 12.5 新增:Compaction 階段是否觸發 timeout(架構 §8.1「失敗旗標」對稱 insufficient_data)。
 *
 * 與 `NeelyDiagnostics.compaction_timeout` 雙寫 — 對齊 spec §8.1 把兩個失敗旗標
 * 都放 Output 頂層,但保留 Diagnostics 內版本以維持向下相容。
 */
compaction_timeout: boolean, 
/**
 * Stage 3.5 Pattern Isolation 識別出的形態邊界(Phase 3 PR)。
 * 對齊 m3Spec/neely_rules.md §Pattern Isolation Procedures。
 */
pattern_bounds: Array<PatternBound>, 
/**
 * Stage 3.5 Zigzag DETOUR Test annotation(Phase 3 PR)。
 * 對齊 m3Spec/neely_rules.md §Zigzag DETOUR Test。
 */
detour_annotations: Array<DetourAnnotation>, 
/**
 * Phase 8 新增:Three Rounds Round 3 暫停資訊(architecture §8.4)。
 * 圖中無任何 :L5/:L3 base label → 進入 Round 3 暫停;否則 None。
 */
round3_pause: Round3PauseInfo | null, 
/**
 * Phase 9 新增:Stage 9a Missing Wave 偵測結果(spec Ch12 + 1054-1057 missing wave 標記慣例)。
 */
missing_wave_suspects: Array<MissingWaveSuspect>, 
/**
 * Phase 9 新增:Stage 9b Emulation 偵測結果(spec Ch12 Emulation)。
 */
emulation_suspects: Array<EmulationSuspect>, 
/**
 * Phase 10 新增:Stage 10.5 Reverse Logic 觀察(spec §Expansion of Possibilities)。
 * 同一資料序列存在多套合法計數時觸發 — 市場處於某更大形態的中段。
 */
reverse_logic_observation: ReverseLogicObservation | null, 
/**
 * Phase 12 新增:Stage 11 Degree Ceiling 推導(architecture §8.5 / §13.3)。
 * 依資料量自動推導本次分析能達到的最高 Degree。
 */
degree_ceiling: DegreeCeiling, 
/**
 * Phase 12 新增:Stage 12 cross_timeframe_hints(architecture §8.6 / §3.4)。
 * 各 monowave 的 Structure Label + 價格區間摘要,供 Aggregation Layer 跨 Timeframe 比對。
 */
cross_timeframe_hints: CrossTimeframeHints, 
/**
 * Fusion Layer P1.1:全 forest scenario 的 `expected_fib_zones` 去重聯集
 * (對齊 m3Spec/fusion_layer.md §6 #1)。供 Fusion `key_levels` 模組直接讀,
 * 不必每次重跑 Neely。
 */
flat_fib_zones: Array<FibZone>, };
