// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuleRejection } from "./RuleRejection";
import type { ShadowCompactionDiagnostics } from "./ShadowCompactionDiagnostics";

export type NeelyDiagnostics = { monowave_count: number, candidate_count: number, validator_pass_count: number, validator_reject_count: number, 
/**
 * 完整保留拒絕原因(§18.1):rule_id / expected / actual / gap / neely_page
 */
rejections: Array<RuleRejection>, forest_size: number, 
/**
 * 所有合法壓縮路徑
 */
compaction_paths: number, 
/**
 * Forest 是否爆量觸發 BeamSearchFallback
 */
overflow_triggered: boolean, 
/**
 * Compaction 是否逾時
 */
compaction_timeout: boolean, 
/**
 * 各階段耗時(Stage 0-12,**微秒精度**)。
 *
 * **2026-05-14 P1 fix**:從 ms → μs(Duration::as_micros)。原 ms 精度對 sub-ms
 * stages 截斷成 0(P0 Gate §4 §stage_elapsed 全 0 揭露);改 μs 提供 1000× 精度。
 * SQL caller 用 `(snapshot->'diagnostics'->'stage_elapsed_us'->>'stage_X')::int` 取值。
 */
stage_elapsed_us: { [key in string]?: bigint }, elapsed_ms: bigint, 
/**
 * 峰值記憶體(P0 Gate 校準用)
 */
peak_memory_mb: bigint, 
/**
 * G2.1(m3Spec/neely_compaction_v2.md §3.3):Compaction v2 tiling-round 引擎
 * shadow 雙軌診斷。serving forest 不受影響;G2.4 切換刪舊後本欄退役。
 * JSONB 加欄相容:舊消費端忽略未知欄。
 */
shadow_compaction: ShadowCompactionDiagnostics | null, };
