// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OhlcvBar } from "./OhlcvBar";

/**
 * 後復權 OHLC 序列。Silver `price_*_fwd` 表已處理漲跌停合併與後復權。
 * Volume 為選填,Volume Alignment 子規則(§9.1 `volume_alignment`)需要時用。
 */
export type OhlcvSeries = { stock_id: string, timeframe: "Daily" | "Weekly" | "Monthly" | "Quarterly", bars: Array<OhlcvBar>, };
