// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * W4 與 W2 區 overlap 關係(v4.1 從 `{ label: String }` 升 enum,
 * 給 Aggregation 結構化判斷。對齊 spec §Ch5 Overlap Rule 1326-1329 行)。
 */
export type OverlapPattern = { "Trending": { 
/**
 * W2/W4 區間描述
 */
evidence: string, } } | { "Terminal": { 
/**
 * W4 與 W2 重疊區間描述
 */
evidence: string, } } | "None";
