// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StructureLabel } from "./StructureLabel";

/**
 * Pattern Isolation 識別出的「圖上可隔離的 Elliott 形態邊界」。
 *
 * (start_idx, end_idx) 是 classified_monowaves 的 index 範圍(inclusive)。
 * start_label / end_label 是 anchor 標籤(F3/XC3/L3/S5/L5 之一作為起點,
 * L5/L3 作為終點)。
 */
export type PatternBound = { 
/**
 * 起點 monowave index(inclusive)
 */
start_idx: number, 
/**
 * 終點 monowave index(inclusive)
 */
end_idx: number, 
/**
 * 起點 anchor 標籤(spec 1107 行:F3/XC3/L3/S5/L5 之一)
 */
start_label: StructureLabel, 
/**
 * 終點 anchor 標籤(L5/L3 之一)
 */
end_label: StructureLabel, 
/**
 * 是否通過 Compaction(Ch7)驗證為合法 Elliott 形態(spec Step 5)。
 * Phase 3 預設 false,Phase 6/8(Compaction Three Rounds)實作後填 true。
 */
validated: boolean, 
/**
 * Special Circumstances(spec 1121-1123 行):
 * price action 超出自身起點 → 強制 base = `:3` corrective
 */
forced_corrective: boolean, };
