// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StructureLabel } from "./StructureLabel";

/**
 * Phase 15 新增:Pattern Isolation anchor(spec line 862)。
 *
 * 包裝 `PatternBound` 並標 anchor 起點/終點意圖(start_label / end_label),
 * 供 Aggregation Layer 「依 Pre-Constructive Logic 標籤定位 scenario 在 higher-degree 中的位置」。
 */
export type PatternIsolationAnchor = { 
/**
 * 起點 monowave index(inclusive)
 */
start_idx: number, 
/**
 * 終點 monowave index(inclusive)
 */
end_idx: number, 
/**
 * 起點 anchor 標籤(F3/XC3/L3/S5/L5 之一)
 */
start_label: StructureLabel, 
/**
 * 終點 anchor 標籤(L5/L3 之一)
 */
end_label: StructureLabel, 
/**
 * Compaction(Ch7)驗證為合法 Elliott 形態(Step 5)
 */
validated: boolean, };
