// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WaveNumber } from "./WaveNumber";

/**
 * 後續行為(spec §9.2 line 900–925 r5 結構化 enum)。
 *
 * **舊 3-variant(Continuation/Reversal/Indeterminate)由 Phase 14 取代** —
 * 對齊精華版 Ch10 line 2024–2037「各修正暗示重點」14 種具體後續行為。
 *
 * 由 `power_rating::post_behavior::lookup(pattern_type, power_rating, in_triangle_context)`
 * 查表得出;後續 Stage 5+ 細化規則時可在 classifier 內 override 為 Composite。
 */
export type PostBehavior = "FullRetracementRequired" | { "MinRetracement": { ratio: number, } } | { "ReachesWaveZone": { wave: WaveNumber, } } | { "NextImpulseExceeds": { ratio: number, } } | { "NotFullyRetracedUnless": { exception: string, } } | "Unconstrained" | { "HintsAtPattern": { suggested_pattern: string, reason: string, } } | { "Composite": { behaviors: Array<PostBehavior>, } };
