// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reverse Logic Observation — 多套合法計數場景的觀察輸出。
 *
 * 對齊 spec 2599 行核心定理:
 *   「同一資料序列存在多個完美合法的計數時,市場必定處於某個修正/衝動形態的中央
 *   (b 的 b、3 的 3、或 Non-Standard 複雜修正的 x)。可能性越多,越靠近中央。」
 *
 * 操作意涵(spec 2601-2604 行):
 *   - 觀察到多套合理計數 → 自動剔除「形態即將完成」的選項,只保留「市場處於中段」的解讀
 *   - 若尚未進場 → 等到可能性收斂為一再進場
 *   - 若已持倉獲利 → 多套計數出現不代表頂底,而是還有路要走
 */
export type ReverseLogicObservation = { 
/**
 * 同一資料上有效 scenario 的數量(forest.len())
 */
scenario_count: number, 
/**
 * 是否觸發 Reverse Logic 操作意涵(scenario_count >= 閾值)
 */
triggered: boolean, 
/**
 * 機械式陳述(對齊 cores_overview §6.1.1 禁主觀詞彙)
 */
message: string, 
/**
 * 建議過濾掉的「形態即將完成」scenario id 列表
 * (spec 2602 行「自動剔除『形態即將完成』的選項」操作意涵)
 */
suggested_filter_ids: Array<string>, };
