// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Phase 15 新增:Three Rounds 狀態。
 *
 * 對齊 m3Spec/neely_rules.md §Ch4(1200-1290 行):
 *   - Round 1:初始 Series 識別(從 Pre-Constructive Logic 標的 monowaves 找出 Standard/Non-Standard)
 *   - Round 2:Compaction 後重評估(`compacted_base_label` 已填,base label 已 reassign 為 :5 / :3)
 *   - Round 3Pause:圖中無新 :L5/:L3,等候(awaiting_l_label = true)
 *
 * 由 classifier 階段依 `compacted_base_label` + `awaiting_l_label` 推導:
 *   - awaiting_l_label = true → Round3Pause
 *   - compacted_base_label 已 reassign(非預設)+ awaiting = false → Round2
 *   - 否則 → Round1
 */
export type RoundState = "Round1" | "Round2" | "Round3Pause";
