// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Three Rounds Round 3 暫停資訊(neely_core_architecture.md §8.4)。
 */
export type Round3PauseInfo = { 
/**
 * Round 3 觸發原因說明
 */
reason: string, 
/**
 * 受影響的 scenario id 數量(全 forest 都標 awaiting_l_label)
 */
affected_scenario_count: number, };
