// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuleId } from "./RuleId";

export type RuleRejection = { candidate_id: string, rule_id: RuleId, expected: string, actual: string, 
/**
 * 偏離量(百分比或絕對值,依規則而定)
 */
gap: number, 
/**
 * Neely 書頁追溯,例 "p.123"
 */
neely_page: string, };
