// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdvisoryFinding } from "./AdvisoryFinding";
import type { ComplexityLevel } from "./ComplexityLevel";
import type { FibZone } from "./FibZone";
import type { MonowaveDirection } from "./MonowaveDirection";
import type { MonowaveStructureLabels } from "./MonowaveStructureLabels";
import type { NeelyPatternType } from "./NeelyPatternType";
import type { PatternIsolationAnchor } from "./PatternIsolationAnchor";
import type { PostBehavior } from "./PostBehavior";
import type { PowerRating } from "./PowerRating";
import type { RoundState } from "./RoundState";
import type { RuleId } from "./RuleId";
import type { StructuralFacts } from "./StructuralFacts";
import type { StructureLabel } from "./StructureLabel";
import type { Trigger } from "./Trigger";
import type { WaveNode } from "./WaveNode";

export type Scenario = { id: string, wave_tree: WaveNode, pattern_type: NeelyPatternType, 
/**
 * candidate 起始 monowave direction(Phase 5 PR 新增,供 Power Rating 判 Bullish/Bearish 符號)
 */
initial_direction: MonowaveDirection, 
/**
 * Phase 6 新增:Ch7 Compaction Reassessment 後的 base structure label。
 *
 * 對齊 m3Spec/neely_rules.md §Compaction 表(1803-1811 行):
 *   - Trending Impulse / Terminal Impulse → `:5`
 *   - Zigzag / Flat / Triangle / 含 x-wave 形態 → `:3`
 *
 * 供更高級的 Compaction Round 1 重新評估該 scenario 在更大序列裡的角色。
 */
compacted_base_label: StructureLabel, 
/**
 * 例:"5-3-5 Zigzag in W4 of larger Impulse"
 */
structure_label: string, complexity_level: ComplexityLevel, 
/**
 * r3 修正:由 i8 改 enum,避免 power_rating = 99 等無效值(§9.4)
 */
power_rating: PowerRating, 
/**
 * Power Rating 對應的最大回測比例(精華版 Ch10 表 2016-2022 行)。
 *
 * 對齊 m3Spec/neely_core_architecture.md §9.1:`max_retracement: Option<f64>`
 * - `None` = 任意回測(Neutral / 或 Triangle/Terminal 內部覆蓋)
 * - `Some(0.90)` = ±1 級 ≤ 90%
 * - `Some(0.80)` = ±2 級 ≤ 80%
 * - `Some(0.65)` = ±3 級 ≤ 60–70%(取中值)
 *
 * 由 `power_rating::max_retracement::lookup` 依 PowerRating + in_triangle_context 查表。
 */
max_retracement: number | null, post_pattern_behavior: PostBehavior, 
/**
 * 客觀計數(取代 v1.1 主觀分數)
 */
passed_rules: Array<RuleId>, deferred_rules: Array<RuleId>, rules_passed_count: number, deferred_rules_count: number, 
/**
 * 失效條件(Neely 規則的逆向轉譯)
 */
invalidation_triggers: Array<Trigger>, 
/**
 * Fibonacci 投影區
 */
expected_fib_zones: Array<FibZone>, 
/**
 * 結構性事實 7 維(Item 7 拆解,不加總)
 */
structural_facts: StructuralFacts, 
/**
 * Phase 7 新增:Stage 7.5 Channeling + Ch9 Advanced Rules 的諮詢性發現。
 * 對齊 m3Spec/neely_rules.md §Ch5 Channeling + §Ch9 Advanced Rules。
 * 諮詢性 — 不直接影響 pattern_complete,提供下游 Aggregation Layer 使用。
 */
advisory_findings: Array<AdvisoryFinding>, 
/**
 * Phase 8 新增:Three Rounds nested parent context — 該 scenario 範圍是否
 * 完全涵蓋於某 Triangle scenario 內。對齊 m3Spec/neely_rules.md §Ch10
 * (2021 行「三角形/Terminal 的內部段不傳遞 Power 暗示」例外)。
 * 由 Stage 8 Compaction 後處理階段填寫;true → Power Rating 套 in_triangle = 0。
 */
in_triangle_context: boolean, 
/**
 * Phase 8 新增:Three Rounds Round 3 暫停標記 — 該 scenario 是否在
 * 「圖中無任何新 :L5/:L3」狀態下標 awaiting。對齊 m3Spec/neely_rules.md
 * §Round 3(1258-1265 行)+ neely_core_architecture.md §8.4 Round3PauseInfo。
 * 策略含意:持有原方向,維持原計數,直到新形態具備收尾條件。
 */
awaiting_l_label: boolean, 
/**
 * 每 wave-monowave 的 Pre-Constructive Structure Label candidates(spec line 859)。
 * 1:1 對應 candidate.monowave_indices 順序;從 ClassifiedMonowave.structure_label_candidates wrap。
 */
monowave_structure_labels: Array<MonowaveStructureLabels>, 
/**
 * Three Rounds 狀態(spec line 860 / §Ch4)— 該 scenario 在 Round 1/2/3 的位置。
 * 由 Stage 8 Three Rounds 階段 + awaiting_l_label 推導。
 */
round_state: RoundState, 
/**
 * Pattern Isolation 6-step procedure 識別出的 anchors(spec line 862)。
 * 從 NeelyCoreOutput.pattern_bounds(Stage 3.5)wrap;只篩涵蓋 scenario 範圍的 anchors。
 */
pattern_isolation_anchors: Array<PatternIsolationAnchor>, 
/**
 * Triplexity 偵測(spec line 863)— Ch8 Triple-grouping(Triple Zigzag / Triple Combination /
 * Triple Three / Triple Three Combination / Triple Three Running)。
 * 由 pattern_type 直接推導。
 */
triplexity_detected: boolean, };
