// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Compaction v2 shadow 雙軌診斷(G2.1;m3Spec/neely_compaction_v2.md §3.3 / §9.3)。
 *
 * tiling-round 引擎(`compaction::round_engine`)每次 compute 隨行,僅寫本結構:
 * - I1–I6 不變量違反計數(§2.2;任一 > 0 = 引擎 bug,Gate v3 紅燈)
 * - `level_cap_hit`(A-8:輪數上限造成的枚舉缺漏,由靜默轉可觀察)
 * - §9.3 shadow 比對計數(舊 forest scenario 依 (start_bar, end_bar, pattern) 被
 *   新引擎節點命中數;召回率門檻於 Gate v3 全階梯後才適用,此處僅計數)
 */
export type ShadowCompactionDiagnostics = { 
/**
 * 引擎版本 tag(例 "tiling-round-g2.1")
 */
engine: string, 
/**
 * base tiling 節點數(非 Neutral monowaves + 合成葉)
 */
base_tiling_len: number, 
/**
 * Neutral 段併入前一 directional 節點的次數(§5.2 合成葉橋接)
 */
neutral_bridged: number, 
/**
 * 開頭 Neutral 無前節點可併,直接排除的數量(記 diagnostics,§5.2)
 */
leading_neutral_dropped: number, 
/**
 * 實際發生聚合的輪數
 */
rounds_run: number, 
/**
 * 收斂後 tiling pool 大小(beam 截斷後)
 */
tiling_count: number, 
/**
 * A-8:觸 max_compaction_levels 上限跳出(非零聚合收斂)
 */
level_cap_hit: boolean, 
/**
 * shadow 引擎自身逾時(不影響 serving `compaction_timeout`)
 */
timed_out: boolean, 
/**
 * W1/I2 防衛在 release 記到的違反數(> 0 = 引擎 bug)
 */
w1_violations: number, 
/**
 * round 內新分支 materialize 上限(round_beam_size × 8)截斷的輪數。
 * 工程護欄非 Neely 語意;> 0 = 該檔枚舉受截斷,Gate 觀測項(A-8 精神)。
 * G2.2 起截斷前先依 beam 鍵近似分數全窗排序,無時間軸偏置
 */
round_branch_cap_hits: number, 
/**
 * G2.2 W5:被 Ch5 端點重驗(overall_pass = false)拒絕的唯一視窗數
 * (§4.1 失敗記錄的 shadow 計數版;完整 RuleRejection 留 G2.4 切換)
 */
w5_rejected_windows: number, 
/**
 * G2.2 Q3 雙軌實驗(§12):完成端點版 vs bars 反查版比對的唯一 5-窗數
 */
q3_windows: number, 
/**
 * Q3:Overlap / 回測判定翻轉的視窗數;翻轉率 = q3_flips / q3_windows,
 * > 5%(spec 初始門檻)→ 落 bars 反查
 */
q3_flips: number, 
/**
 * degree_level → 節點數(canonical 去重後;key 為字串供 JSONB 直取)
 */
node_count_by_level: { [key in string]?: number }, 
/**
 * I1–I6 違反計數(key "I1".."I6")
 */
invariant_violations: { [key in string]?: number }, 
/**
 * §9.3:舊 forest scenario 總數
 */
old_forest_scenarios: number, 
/**
 * §9.3:依 (start_bar, end_bar, pattern_tag) 被新引擎 **degree_level = 1**
 * 節點命中的舊 scenario 數(spec 投影定義;舊 Level ≥ 2 聚合屬預期缺口類別)
 */
old_forest_matched: number, elapsed_us: bigint, };
