// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Compaction v2 shadow 雙軌診斷(G2.1;m3Spec/neely_compaction_v2.md §3.3 / §9.3)。
 *
 * tiling-round 引擎(`compaction::round_engine`)每次 compute 隨行,僅寫本結構:
 * - I1–I6 不變量違反計數(§2.2;任一 > 0 = 引擎 bug,Gate v3 紅燈)
 * - `level_cap_hit`(A-8:輪數上限造成的枚舉缺漏,由靜默轉可觀察)
 * - §9.3 shadow 比對計數(舊 forest scenario 依 (start_bar, end_bar, pattern) 被
 *   新引擎節點命中數;召回率門檻於 Gate v3 全階梯後才適用,此處僅計數)
 */
export type ShadowCompactionDiagnostics = { 
/**
 * 引擎版本 tag(例 "tiling-round-g2.1")
 */
engine: string, 
/**
 * base tiling 節點數(非 Neutral monowaves + 合成葉)
 */
base_tiling_len: number, 
/**
 * Neutral 段併入前一 directional 節點的次數(§5.2 合成葉橋接)
 */
neutral_bridged: number, 
/**
 * 開頭 Neutral 無前節點可併,直接排除的數量(記 diagnostics,§5.2)
 */
leading_neutral_dropped: number, 
/**
 * 實際發生聚合的輪數
 */
rounds_run: number, 
/**
 * 收斂後 tiling pool 大小(beam 截斷後)
 */
tiling_count: number, 
/**
 * A-8:觸 max_compaction_levels 上限跳出(非零聚合收斂)
 */
level_cap_hit: boolean, 
/**
 * shadow 引擎自身逾時(不影響 serving `compaction_timeout`)
 */
timed_out: boolean, 
/**
 * W1/I2 防衛在 release 記到的違反數(> 0 = 引擎 bug)
 */
w1_violations: number, 
/**
 * round 內新分支 materialize 上限(round_beam_size × 8)截斷的輪數。
 * 工程護欄非 Neely 語意;> 0 = 該檔枚舉受截斷,Gate 觀測項(A-8 精神)。
 * G2.2 起截斷前先依 beam 鍵近似分數全窗排序,無時間軸偏置
 */
round_branch_cap_hits: number, 
/**
 * G2.2 W5:被 Ch5 端點重驗(overall_pass = false)拒絕的唯一視窗數
 * (§4.1 失敗記錄的 shadow 計數版;完整 RuleRejection 留 G2.4 切換)
 */
w5_rejected_windows: number, 
/**
 * G2.2 Q3 雙軌實驗(§12):完成端點版 vs bars 反查版比對的唯一 5-窗數
 */
q3_windows: number, 
/**
 * Q3:Overlap / 回測判定翻轉的視窗數;翻轉率 = q3_flips / q3_windows,
 * > 5%(spec 初始門檻)→ 落 bars 反查
 */
q3_flips: number, 
/**
 * degree_level → 節點數(canonical 去重後;key 為字串供 JSONB 直取)
 */
node_count_by_level: { [key in string]?: number }, 
/**
 * G2.4 Gate v3:pattern tag → 節點數(canonical 去重後)— §9.2 Terminal
 * Impulse 存在性門檻與形態分布報告的資料源
 */
node_count_by_pattern: { [key in string]?: number }, 
/**
 * I1–I6 違反計數(key "I1".."I6")
 */
invariant_violations: { [key in string]?: number }, 
/**
 * §9.3:舊 forest scenario 總數
 */
old_forest_scenarios: number, 
/**
 * §9.3:依 (start_bar, end_bar, pattern_tag) 被新引擎 **degree_level = 1**
 * 節點命中的舊 scenario 數(spec 投影定義;舊 Level ≥ 2 聚合屬預期缺口類別)
 */
old_forest_matched: number, 
/**
 * G2.3 §6.1 邊界波重評(D-4):完成比對的 (parent 首/末子波, 真鄰居) 對數
 */
boundary_pairs_checked: number, 
/**
 * §6.1:比值落 [0.236, 0.382) ∪ (2.618, 4.236] 的 Advisory(Info)數
 */
boundary_advisory_info: number, 
/**
 * §6.1:比值落 [0.236, 4.236] 外的 Advisory(Warning)數(不拒絕聚合)
 */
boundary_advisory_warning: number, 
/**
 * §6.1:tiling 首/末 parent 無對應鄰居(或零幅度不可比)跳過的側數
 */
boundary_sides_skipped: number, 
/**
 * G2.3 §6.2 Complexity 真算:complexity level(0..=3)→ 節點數
 * (canonical 去重後收集 forest;取代硬寫 Complex 的分布觀測)
 */
complexity_count_by_level: { [key in string]?: number }, 
/**
 * §6.2:子樹內出現 ≥ 3 種不同 Complexity Level 之 Impulse 段的節點數
 */
triplexity_nodes: number, 
/**
 * G2.3 §6.3 Degree 對映(ceiling 錨定):degree_level → Degree 名
 * (輸出展示用;不回饋任何接受條件)
 */
degree_map: { [key in string]?: string }, 
/**
 * §6.3:超出 11 級下界被夾至 SubMicro 的 level 數(記 diagnostics)
 */
degree_clamped_levels: number, 
/**
 * G2.4 Gate v3 §9.3 逐檔 diff 資料源:degree-1 節點鍵
 * `"{start_bar}-{end_bar}:{pattern_tag}"`(排序後);召回缺口分類
 * (bar 錯位 / tag 變體差 / 視窗缺席)由 verify 腳本離線比對。
 * shadow 期專用,切換時隨本結構移除
 */
degree1_node_keys: Array<string>, 
/**
 * G2.3 A-10:收集 forest 節點以「覆蓋葉 union」語意(PatternBound 完整
 * 落於節點覆蓋 monowave 範圍內)計得的 anchors 總數
 */
anchors_union_total: number, 
/**
 * A-10 對照組:現行「日期範圍重疊即算」近似語意計得的 anchors 總數
 * (收緊幅度 = overlap − union,Gate 觀測)
 */
anchors_overlap_total: number, elapsed_us: bigint, };
