// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlternationFact } from "./AlternationFact";
import type { ChannelingFact } from "./ChannelingFact";
import type { ExtensionSubdivisionPair } from "./ExtensionSubdivisionPair";
import type { FibonacciAlignment } from "./FibonacciAlignment";
import type { OverlapPattern } from "./OverlapPattern";
import type { TimeRelationship } from "./TimeRelationship";
import type { VolumeAlignment } from "./VolumeAlignment";

export type StructuralFacts = { fibonacci_alignment: FibonacciAlignment | null, alternation: AlternationFact | null, channeling: ChannelingFact | null, time_relationship: TimeRelationship | null, 
/**
 * 若有 volume 資料才填(§9.1 註)
 */
volume_alignment: VolumeAlignment | null, gap_count: number, overlap_pattern: OverlapPattern | null, 
/**
 * v4.1:Ch8 Extension vs Subdivision 獨立性判定(對齊 spec §Ch8 Independent Rule)
 */
extension_subdivision_pair: ExtensionSubdivisionPair | null, };
