// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Structure Label — Ch3 Pre-Constructive Logic 輸出於每個 monowave 的「結構候選」標籤。
 *
 * 對應 neely_rules.md §Structure Labels 完整清單(319-346 行)。
 * 命名規則:Position Indicator + Base(`:3` / `:5`),例:
 *   - `F3` = `:F3`(First 修正 3 段)
 *   - `XC3` = `x:c3`(X-wave 變體 c3)
 *   - `BC3` = `b:c3`(Flat b-wave 變體 c3)
 *   - `S5` = `:s5`(Special Five — Neely extension)
 *
 * Phase 2 PR 範圍只宣告 Ch3 引用的 label。未來 Ch4-Ch12 若引入新 label 需擴 enum。
 */
export type StructureLabel = "Five" | "Three" | "F3" | "C3" | "L3" | "UnknownThree" | "F5" | "L5" | "UnknownFive" | "S5" | "SL3" | "SL5" | "XC3" | "BC3" | "BF3";
