// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Certainty } from "./Certainty";
import type { StructureLabel } from "./StructureLabel";

/**
 * Structure Label Candidate — 單一候選 label + certainty。
 */
export type StructureLabelCandidate = { label: StructureLabel, certainty: Certainty, };
