// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ch8 Extension vs Subdivision 獨立性狀態(v4.1 — 對齊 spec §Ch8 Independent Rule)。
 */
export type SubdivisionStatus = "Independent" | "SubordinateToLarger" | "Indeterminate";
