// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Time Relationship 細節(v4.1 — 補 durations + Fibonacci ratio evidence)。
 */
export type TimeRelationship = { label: string, 
/**
 * 各 wave duration in bars(對齊 spec §StructuralFacts.time_relationship)
 */
durations_bars: Array<number>, 
/**
 * W1/W3/W5 時間軸命中的 Fibonacci 比例(0.382 / 0.618 / 1.000 / 1.618 / 2.618;
 * ±10% 容差 / architecture §4.2)
 */
fibonacci_ratios_matched: Array<number>, };
