// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ch11 Triangle 的 a/b/c/d/e 五段標籤。
 * 用於 `RuleId::Ch11_Triangle_Variant_Rules` 指定 Triangle 變體規則對應的 wave。
 */
export type TriangleWave = "A" | "B" | "C" | "D" | "E";
