// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ch11 Triangle 全部變體(neely_rules.md §Triangle — 各變體 2346-2485 行)。
 * 用於 `RuleId::Ch11_Triangle_Variant_Rules` 區分 9 種 Triangle 變體規則。
 *
 * 三種型態(Horizontal / Irregular / Running)× 三種類型(Limiting / Non-Limiting / Expanding)
 * = 9 變體。
 */
export type TriangleVariant = "HorizontalLimiting" | "IrregularLimiting" | "RunningLimiting" | "HorizontalNonLimiting" | "IrregularNonLimiting" | "RunningNonLimiting" | "HorizontalExpanding" | "IrregularExpanding" | "RunningExpanding";
