// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TriggerType = { "PriceBreakBelow": number } | { "PriceBreakAbove": number } | { "TimeExceeds": string } | { "VolumeAnomaly": { z_threshold: number, } } | { "OverlapWith": { wave_id: string, } };
