// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OnTriggerAction } from "./OnTriggerAction";
import type { RuleId } from "./RuleId";
import type { TriggerType } from "./TriggerType";

export type Trigger = { trigger_type: TriggerType, 
/**
 * r3 修正:移除 ReduceProbability,改 WeakenScenario(§9.4)
 */
on_trigger: OnTriggerAction, rule_reference: RuleId, neely_page: string, };
