// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StructureLabel } from "./StructureLabel";

/**
 * Wave Tree(階層化波浪結構)。
 *
 * **G2.4 契約協調(compaction v2 §7.3)**:加 `degree_level` / `base_label`
 * 兩欄(JSONB 加欄不刪欄,舊消費端忽略未知欄)— 巢狀展示與 MCP 語意必需。
 * 現行(切換前)引擎為 best-effort 填值:root = 形態層(degree 1 起)、
 * 葉 = monowave leg(degree 0,label 取 Stage 0 Primary 候選,無則依 slot);
 * tiling-round 引擎切換後由 CompactionNode 凍結為真值。
 */
export type WaveNode = { label: string, start: string, end: string, 
/**
 * 葉(monowave leg)= 0;parent = max(children) + 1(compaction v2 I4)
 */
degree_level: number, 
/**
 * `:3` / `:5` 前端標示(compaction v2 I5;葉為 Stage 0 標籤或 slot 推定)
 */
base_label: StructureLabel, children: Array<WaveNode>, };
