// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Neely wave number 標號(Impulse 1-5 + Combination X + Triangle/Flat A-E)。
 *
 * 對齊 m3Spec/neely_core_architecture.md §9.2 PostBehavior::ReachesWaveZone 內部欄。
 */
export type WaveNumber = "W1" | "W2" | "W3" | "W4" | "W5" | "WX" | "WA" | "WB" | "WC" | "WD" | "WE";
