// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ch11 Flat / Zigzag 的 a/b/c 三段標籤。
 * 用於 `RuleId::Ch11_Flat_Variant_Rules` / `Ch11_Zigzag_WaveByWave` 指定變體規則對應的 wave。
 */
export type WaveAbc = "A" | "B" | "C";
