// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wave Tree(階層化波浪結構)。具體欄位於後續 PR 補完。
 */
export type WaveNode = { label: string, start: string, end: string, children: Array<WaveNode>, };
