// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KalmanEventKind } from "./KalmanEventKind";

export type KalmanEvent = { date: string, kind: KalmanEventKind, 
/**
 * fact_schema::with_event_kind 慣例:`{ event_kind: string, ... }`(任意附加欄)
 */
metadata: Record<string, unknown>, };
