// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Regime } from "./Regime";

export type KalmanPoint = { date: string, raw_close: number, smoothed_price: number, uncertainty: number, velocity: number, regime: Regime, };
