// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KalmanPoint } from "./KalmanPoint";

/**
 * v3.33:per-horizon output(只記 latest state + event count,full series 不存
 * 避免 indicator_values JSONB 體積膨脹 4×)。
 */
export type KalmanHorizonOutput = { label: string, process_noise_q: number, halflife_bars: number, velocity_threshold_pct: number, min_regime_duration_days: number, 
/**
 * 該 horizon 的 series 最末 state(對齊 v3.30 series-last-entry path 慣例)
 */
series_last: KalmanPoint | null, 
/**
 * 該 horizon transition event 數(facts 只走 primary,但其他 horizon 仍可參考)
 */
event_count: number, };
