// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KalmanEvent } from "./KalmanEvent";
import type { KalmanHorizonOutput } from "./KalmanHorizonOutput";
import type { KalmanPoint } from "./KalmanPoint";

export type KalmanFilterOutput = { stock_id: string, timeframe: "Daily" | "Weekly" | "Monthly" | "Quarterly", 
/**
 * primary horizon label(top-level `series` + `events` 對齊此 horizon)
 */
primary_horizon: string, 
/**
 * primary horizon 完整 series(backward compat v3.30 series-last-entry path)
 */
series: Array<KalmanPoint>, 
/**
 * primary horizon events(對齊 produce_facts 來源)
 */
events: Array<KalmanEvent>, 
/**
 * v3.33:4 horizons 的 latest state + event_count
 */
horizons: Array<KalmanHorizonOutput>, };
